# Data Exploration Notebook

This notebook helps profile the **raw datar** and define the **transformations**.

In [1]:
%pip install pandas

import pandas as pd
import os

Requirement already satisfied: pandas in d:\onedrive\documentos\entrevistas de emprego\projetos\job-market-analytics-warehouse\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in d:\onedrive\documentos\entrevistas de emprego\projetos\job-market-analytics-warehouse\.venv\lib\site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\onedrive\documentos\entrevistas de emprego\projetos\job-market-analytics-warehouse\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\onedrive\documentos\entrevistas de emprego\projetos\job-market-analytics-warehouse\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in d:\onedrive\documentos\entrevistas de emprego\projetos\job-market-analytics-warehouse\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in d:\onedrive\documentos\entrevistas de emprego\projetos\job-market-analytics-warehouse\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## 1) Select raw data

In [2]:
folder_path = "../raw/"
raw_path = os.listdir(folder_path)
raw_data_path = ""
last_ingestion = 0

for filename in raw_path:
	if "jobs_" in filename and filename.endswith(".jsonl"):
		date_part  = filename.split("jobs_")[-1].split(".jsonl")[0]
		max_date = int(date_part.replace("_", ""))
		if max_date > last_ingestion:
		 	raw_data_path = filename

if not raw_data_path:
	raise ValueError("Raw data path not found.")
else:
	final_path = folder_path + raw_data_path
	df = pd.read_json(final_path, lines=True)
	# Initial conferences
	print(f"Rows count: {len(df):,}")
	print(f"Columns count: {len(df.columns)}")
	print(f"Columns: {df.columns}")

Rows count: 701
Columns count: 5
Columns: Index(['source', 'search_keyword', 'search_location', 'scraped_at', 'raw'], dtype='object')

In [3]:
# Transform 'raw' column dict in DataFrame
df_raw_columns = pd.json_normalize(df['raw'])
df = pd.concat([df, df_raw_columns], axis=1)
df = df.drop(columns=['raw'])

df.columns

Index(['source', 'search_keyword', 'search_location', 'scraped_at', 'id',
       'site', 'job_url', 'job_url_direct', 'title', 'company', 'location',
       'date_posted', 'job_type', 'salary_source', 'interval', 'min_amount',
       'max_amount', 'currency', 'is_remote', 'job_level', 'job_function',
       'listing_type', 'emails', 'description', 'company_industry',
       'company_url', 'company_logo', 'company_url_direct',
       'company_addresses', 'company_num_employees', 'company_revenue',
       'company_description', 'skills', 'experience_range', 'company_rating',
       'company_reviews_count', 'vacancy_count', 'work_from_home_type'],
      dtype='object')

## 2) Basic schema profiling

In [4]:
schema_df = pd.DataFrame({
    "column": df.columns,
    "dtype": [str(df[c].dtype) for c in df.columns],
    "non_null": [int(df[c].notna().sum()) for c in df.columns],
    "nulls": [int(df[c].isna().sum()) for c in df.columns],
    "null_pct": [round(df[c].isna().mean() * 100, 2) for c in df.columns],
    "n_unique": [int(df[c].nunique(dropna=True)) for c in df.columns],
}).sort_values(["null_pct", "column"], ascending=[False, True])

schema_df

,column,dtype,non_null,nulls,null_pct,n_unique
34,company_rating,object,0,701,100.00,0
35,company_reviews_count,object,0,701,100.00,0
17,currency,object,0,701,100.00,0
33,experience_range,object,0,701,100.00,0
14,interval,object,0,701,100.00,0
21,listing_type,object,0,701,100.00,0
16,max_amount,object,0,701,100.00,0
15,min_amount,object,0,701,100.00,0
13,salary_source,object,0,701,100.00,0
32,skills,object,0,701,100.00,0
36,vacancy_count,object,0,701,100.00,0
37,work_from_home_type,object,0,701,100.00,0
22,emails,object,149,552,78.74,57
30,company_revenue,object,200,501,71.47,9
31,company_description,object,203,498,71.04,54
28,company_addresses,object,260,441,62.91,61
29,company_num_employees,object,266,435,62.05,9
27,company_url_direct,object,277,424,60.49,85
7,job_url_direct,object,341,360,51.36,149
20,job_function,object,360,341,48.64,33
19,job_level,object,360,341,48.64,6
24,company_industry,object,426,275,39.23,71
26,company_logo,object,632,69,9.84,220
12,job_type,object,641,60,8.56,11
11,date_posted,object,660,41,5.85,9
9,company,object,693,8,1.14,227
25,company_url,object,700,1,0.14,243
23,description,object,701,0,0.00,344
4,id,object,701,0,0.00,385
18,is_remote,bool,701,0,0.00,2
6,job_url,object,701,0,0.00,385
10,location,object,701,0,0.00,81
3,scraped_at,"datetime64[ns, UTC]",701,0,0.00,20
1,search_keyword,object,701,0,0.00,2
2,search_location,object,701,0,0.00,5
5,site,object,701,0,0.00,2
0,source,object,701,0,0.00,2
8,title,object,701,0,0.00,265

In [5]:
# Check the need to be normalized in Silver
key_dims = [c for c in df.columns]
for col in key_dims:
    print(f"\n=== {col} ===")
    display(
        df[col]
        .astype("string")
        .str.strip()
        .fillna("<NULL>")
        .value_counts(dropna=False)
        .head(10)
        .to_frame("count")
    )

=== source ===

          count
source
linkedin    360
indeed      341

=== search_keyword ===

                  count
search_keyword
data engineer       443
ai data engineer    258

=== search_location ===

                      count
search_location
Australia               303
Sydney, Australia       191
Melbourne, Australia    107
Brisbane, Australia      59
Perth, Australia         41

=== scraped_at ===

                                  count
scraped_at
2026-06-20 22:09:12.879996+00:00    100
2026-06-20 22:04:12.404817+00:00     80
2026-06-20 22:09:03.642112+00:00     72
2026-06-20 22:08:59.845507+00:00     67
2026-06-20 22:09:22.096130+00:00     56
2026-06-20 21:59:16.559146+00:00     49
2026-06-20 22:00:30.385755+00:00     38
2026-06-20 22:05:18.673246+00:00     37
2026-06-20 22:09:15.483358+00:00     33
2026-06-20 22:09:05.921844+00:00     32

=== id ===

                     count
id
in-7b8304edff45b559      4
li-4418124632            4
in-276bc8391721f749      4
in-072bb60a80ffce12      4
in-c9e05766078c764d      4
in-6f21c9f51339d077      4
in-aa95902d2ef0ccfc      4
in-905390aefbcf8f92      4
in-db2fb3cc92a93e9c      4
in-75e1e7bb6384ed11      4

=== site ===

          count
site
linkedin    360
indeed      341

=== job_url ===

                                                   count
job_url
https://au.indeed.com/viewjob?jk=7b8304edff45b559      4
https://www.linkedin.com/jobs/view/4418124632          4
https://au.indeed.com/viewjob?jk=276bc8391721f749      4
https://au.indeed.com/viewjob?jk=072bb60a80ffce12      4
https://au.indeed.com/viewjob?jk=c9e05766078c764d      4
https://au.indeed.com/viewjob?jk=6f21c9f51339d077      4
https://au.indeed.com/viewjob?jk=aa95902d2ef0ccfc      4
https://au.indeed.com/viewjob?jk=905390aefbcf8f92      4
https://au.indeed.com/viewjob?jk=db2fb3cc92a93e9c      4
https://au.indeed.com/viewjob?jk=75e1e7bb6384ed11      4

=== job_url_direct ===

                                                    count
job_url_direct
<NULL>                                                360
https://careers.google.com/jobs/results/1087515...      8
https://careers.google.com/jobs/results/1375937...      7
https://grnh.se/cmlqx9rn4us                             7
https://h2oai./apply/VLqqYhStLs/Lead-AI-Enginee...      4
https://jobs.lever.co/safetyculture-2/352fdb48-...      4
https://careers.alvarezandmarsal.com/jobs/17889337      4
https://jobs.smartrecruiters.com/Canva/60000000...      4
https://employmenthero.com/jobs/position/intell...      4
https://magentus.teamtailor.com/jobs/7940278-te...      4

=== title ===

                                                    count
title
Senior Data Engineer                                   30
Data Engineer                                          29
AI Engineer                                            17
Software Engineer                                      15
Senior AI Engineer                                     15
Senior Software Engineer                               13
Data Analyst - Power System Modelling                  10
Principal Data Engineer                                 9
Lead Software Engineer                                  9
Customer Engineer Associate, Platform, Google C...      8

=== company ===

                                          count
company
H2O.ai                                       28
Amazon Web Services                          19
Karbon                                       17
Australian Energy Market Operator (AEMO)     16
Google                                       16
Accenture Australia                          15
Squiz                                        12
SAFETYCULTURE                                11
Future Secure AI                             11
Boeing                                       10

=== location ===

                                     count
location
Sydney, NSW, AU                        144
Sydney, New South Wales, Australia     134
Melbourne, Victoria, Australia          83
Melbourne, VIC, AU                      47
Brisbane, Queensland, Australia         34
                                        34
Perth, Western Australia, Australia     26
Brisbane, QLD, AU                       25
Perth, WA, AU                           17
Docklands, VIC, AU                       8

=== date_posted ===

             count
date_posted
2026-06-19     328
2026-06-18     261
<NULL>          41
2026-06-17      39
2026-06-20       8
2026-06-16       8
2026-06-11       8
2026-06-05       4
2026-03-06       3
2026-05-28       1

=== job_type ===

                     count
job_type
fulltime               561
<NULL>                  60
contract                46
parttime                11
other                    5
temporary, fulltime      4
internship               3
volunteer                3
temporary                2
fulltime, contract       2

=== salary_source ===

               count
salary_source
<NULL>           701

=== interval ===

          count
interval
<NULL>      701

=== min_amount ===

            count
min_amount
<NULL>        701

=== max_amount ===

            count
max_amount
<NULL>        701

=== currency ===

          count
currency
<NULL>      701

=== is_remote ===

           count
is_remote
False        532
True         169

=== job_level ===

                  count
job_level
<NULL>              341
mid-senior level    258
entry level          42
not applicable       38
associate            14
internship            5
director              3

=== job_function ===

                                        count
job_function
<NULL>                                    341
Information Technology                    138
Engineering and Information Technology    135
Engineering                                15
Other                                       7
Education, Research, and Science            7
Information Technology and Engineering      7
Analyst and Information Technology          5
Consulting                                  5
Information Technology and Finance          4

=== listing_type ===

              count
listing_type
<NULL>          701

=== emails ===

                                                    count
emails
<NULL>                                                552
people.support@karbonhq.com                            17
talent@aemo.com.au                                     16
exectalent@accenture.com                                9
careers.au@au.leidos.com, LeidosCareersFraud@le...      7
recruiting@crowdstrike.com                              6
-Careers@cae.com                                        4
nab.careers@nab.com.au                                  4
globaltalentss@servicenow.com                           4
contact@anduril.com, contact@anduril.com                4

=== description ===

                                                    count
description
Division: Operations\n   \n\n  \n\n Department:...     10
At Google, we have a vision of empowerment and ...      8
**About the Company** \n\n\n\n\n  \n \n\n\n\n A...      7
At Google, we have a vision of empowerment and ...      7
**About Karbon**\n\n\n\nKarbon is the global le...      7
**Job description** \n\n\n\n\n Are you a detail...      6
**About The Job**\n We are looking for existing...      6
The Squiz product team is working to deliver a ...      5
Division: System Design\n   \n\n  \n\n Departme...      5
*Australia \| Full\-time \| Hybrid or Remote*\n...      4

=== company_industry ===

                                                    count
company_industry
<NULL>                                                275
Software Development                                   72
IT Services and IT Consulting                          62
Financial Services                                     29
Business Consulting and Services                       18
Utilities                                              16
Non-profit Organizations and Primary and Second...     14
Government                                             13
Banking, Financial Services, and Investment Ban...     11
Consulting And Business Services                       10

=== company_url ===

                                                    count
company_url
https://au.indeed.com/cmp/H2o.ai                       20
https://au.indeed.com/cmp/Amazon-Web-Services-0...     19
https://au.linkedin.com/company/australian-ener...     16
https://au.linkedin.com/company/accentureaustralia     15
https://au.indeed.com/cmp/Google                       15
https://au.linkedin.com/company/squiz                  12
https://au.indeed.com/cmp/Safetyculture                11
https://www.linkedin.com/company/future-secure-ai      11
https://au.indeed.com/cmp/Karbon                       11
https://au.linkedin.com/company/commonwealthbank        9

=== company_logo ===

                                                    count
company_logo
<NULL>                                                 69
https://d2q79iu7y748jz.cloudfront.net/s/_square...     20
https://d2q79iu7y748jz.cloudfront.net/s/_square...     19
https://media.licdn.com/dms/image/v2/C560BAQHFe...     16
https://media.licdn.com/dms/image/v2/D560BAQFIE...     15
https://d2q79iu7y748jz.cloudfront.net/s/_square...     15
https://media.licdn.com/dms/image/v2/C560BAQFkB...     12
https://d2q79iu7y748jz.cloudfront.net/s/_square...     11
https://d2q79iu7y748jz.cloudfront.net/s/_square...     11
https://media.licdn.com/dms/image/v2/D560BAQGTW...     11

=== company_url_direct ===

                                               count
company_url_direct
<NULL>                                           424
http://www.h2o.ai                                 20
https://aws.amazon.com/careers/why-aws/           19
http://goo.gle/3ygdkgv                            15
https://safetyculture.com/                        11
https://karbonhq.com/                             11
https://www.alvarezandmarsal.com/                  8
https://careers.services.global.ntt/global/en      8
http://www.commbank.com.au                         7
https://www.boeing.com                             7

=== company_addresses ===

                                                    count
company_addresses
<NULL>                                                441
Sydney                                                 36
Seattle, WA                                            23
Mountain View                                          20
Mountain View, CA                                      15
2 Lacey Street Surry Hills NSW 2010 Australia          11
United States\r\nCanada\r\nNew Zealand\r\nAustr...     11
New York, NY                                            8
Tokyo                                                   8
Washington, DC                                          7

=== company_num_employees ===

                       count
company_num_employees
<NULL>                   435
10,000+                  126
1,001 to 5,000            30
11 to 50                  25
51 to 200                 25
Decline to state          19
201 to 500                17
501 to 1,000               9
5,001 to 10,000            9
2 to 10                    6

=== company_revenue ===

                      count
company_revenue
<NULL>                  501
more than $10B (USD)     98
$1B to $5B (USD)         29
less than $1M (USD)      21
$5B to $10B (USD)        19
$500M to $1B (USD)       13
$100M to $500M (USD)      7
Decline to state          6
$5M to $25M (USD)         4
$25M to $100M (USD)       3

=== company_description ===

                                                    count
company_description
<NULL>                                                498
Amazon Web Services (AWS) offers the world’s mo...     19
Our mission is to organize the world’s informat...     15
                                                       15
Our mission is to help companies achieve safer ...     11
We’re on a mission to change the way accounting...     11
Own your career with NTT DATA\nJoin a global bu...      8
Alvarez & Marsal (A&M) is a global professional...      8
Boeing is the world's largest aerospace company...      7
Or purpose is to improve the financial well-bei...      7

=== skills ===

        count
skills
<NULL>    701

=== experience_range ===

                  count
experience_range
<NULL>              701

=== company_rating ===

                count
company_rating
<NULL>            701

=== company_reviews_count ===

                       count
company_reviews_count
<NULL>                   701

=== vacancy_count ===

               count
vacancy_count
<NULL>           701

=== work_from_home_type ===

                     count
work_from_home_type
<NULL>                 701

## 3) Duplicate and key profiling

In [6]:
if "id" in df.columns:
    dup_count = int(df.duplicated(subset=["id", "source"]).sum())
    print("Duplicated id per source:", dup_count)

    if dup_count:
        display(df[df.duplicated(subset=["id", "source"], keep=False)].sort_values("id").head(10))
else:
    print("Column 'id' not found.")

Duplicated id per source: 316

,source,search_keyword,search_location,scraped_at,id,site,job_url,job_url_direct,title,company,...,company_addresses,company_num_employees,company_revenue,company_description,skills,experience_range,company_rating,company_reviews_count,vacancy_count,work_from_home_type
394,indeed,data engineer,"Sydney, Australia",2026-06-20 22:09:03.642112+00:00,in-00e3024154fb2516,indeed,https://au.indeed.com/viewjob?jk=00e3024154fb2516,https://iworkfor.nsw.gov.au/job/engineer-584213,Engineer,NSW Government,...,Sydney,"10,000+",None,None,None,None,None,None,None,None
560,indeed,data engineer,Australia,2026-06-20 22:09:12.879996+00:00,in-00e3024154fb2516,indeed,https://au.indeed.com/viewjob?jk=00e3024154fb2516,https://iworkfor.nsw.gov.au/job/engineer-584213,Engineer,NSW Government,...,Sydney,"10,000+",None,None,None,None,None,None,None,None
627,indeed,ai data engineer,"Sydney, Australia",2026-06-20 22:09:15.483358+00:00,in-01492af9a249ba09,indeed,https://au.indeed.com/viewjob?jk=01492af9a249ba09,https://h2oai./apply/h6ZS1I79Ik/AI-Engineer?so...,AI Engineer,H2O.ai,...,Mountain View,11 to 50,less than $1M (USD),None,None,None,None,None,None,None
693,indeed,ai data engineer,Australia,2026-06-20 22:09:22.096130+00:00,in-01492af9a249ba09,indeed,https://au.indeed.com/viewjob?jk=01492af9a249ba09,https://h2oai./apply/h6ZS1I79Ik/AI-Engineer?so...,AI Engineer,H2O.ai,...,Mountain View,11 to 50,less than $1M (USD),None,None,None,None,None,None,None
421,indeed,data engineer,"Sydney, Australia",2026-06-20 22:09:03.642112+00:00,in-01492af9a249ba09,indeed,https://au.indeed.com/viewjob?jk=01492af9a249ba09,https://h2oai./apply/h6ZS1I79Ik/AI-Engineer?so...,AI Engineer,H2O.ai,...,Mountain View,11 to 50,less than $1M (USD),None,None,None,None,None,None,None
584,indeed,data engineer,Australia,2026-06-20 22:09:12.879996+00:00,in-01492af9a249ba09,indeed,https://au.indeed.com/viewjob?jk=01492af9a249ba09,https://h2oai./apply/h6ZS1I79Ik/AI-Engineer?so...,AI Engineer,H2O.ai,...,Mountain View,11 to 50,less than $1M (USD),None,None,None,None,None,None,None
407,indeed,data engineer,"Sydney, Australia",2026-06-20 22:09:03.642112+00:00,in-026ef088eca5582a,indeed,https://au.indeed.com/viewjob?jk=026ef088eca5582a,https://grnh.se/cmlqx9rn4us,Lead Software Engineer,Karbon,...,United States\r\nCanada\r\nNew Zealand\r\nAust...,51 to 200,None,We’re on a mission to change the way accountin...,None,None,None,None,None,None
683,indeed,ai data engineer,Australia,2026-06-20 22:09:22.096130+00:00,in-026ef088eca5582a,indeed,https://au.indeed.com/viewjob?jk=026ef088eca5582a,https://grnh.se/cmlqx9rn4us,Lead Software Engineer,Karbon,...,United States\r\nCanada\r\nNew Zealand\r\nAust...,51 to 200,None,We’re on a mission to change the way accountin...,None,None,None,None,None,None
619,indeed,ai data engineer,"Sydney, Australia",2026-06-20 22:09:15.483358+00:00,in-026ef088eca5582a,indeed,https://au.indeed.com/viewjob?jk=026ef088eca5582a,https://grnh.se/cmlqx9rn4us,Lead Software Engineer,Karbon,...,United States\r\nCanada\r\nNew Zealand\r\nAust...,51 to 200,None,We’re on a mission to change the way accountin...,None,None,None,None,None,None
671,indeed,ai data engineer,Australia,2026-06-20 22:09:22.096130+00:00,in-04d2eb56fba078d5,indeed,https://au.indeed.com/viewjob?jk=04d2eb56fba078d5,https://jobs.lever.co/immuta/d56a5011-8fbd-4b1...,Solutions Engineer,Immuta,...,College Park,51 to 200,None,None,None,None,None,None,None,None